--Creación del usuario con el que se crearan las tablas.
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
CREATE USER evento_sostenible IDENTIFIED BY evento_sostenible QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO evento_sostenible;

-- TABLA UBICACION
CREATE TABLE UBICACION (
    ID_UBICACION NUMBER(10) NOT NULL,
    CIUDAD VARCHAR2(100) NOT NULL,
    DIRECCION VARCHAR2(200) NOT NULL,
    TIPO VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_UBICACION PRIMARY KEY (ID_UBICACION)
);

-- TABLA USUARIO
CREATE TABLE USUARIO (
    ID_USUARIO NUMBER(10) NOT NULL,
    NOMBRE VARCHAR2(100) NOT NULL,
    CORREO VARCHAR2(100) NOT NULL,
    CONTRASENA VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO)
);

-- TABLA ORGANIZADOR
CREATE TABLE ORGANIZADOR (
    ID_ORGANIZADOR NUMBER(10) NOT NULL,
    NOMBRE VARCHAR2(100) NOT NULL,
    CONTACTO VARCHAR2(100) NOT NULL,
    CORREO VARCHAR2(100) NOT NULL,
    TELEFONO VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_ORGANIZADOR PRIMARY KEY (ID_ORGANIZADOR)
);

-- TABLA CATEGORIA
CREATE TABLE CATEGORIA (
    ID_CATEGORIA NUMBER(10) NOT NULL,
    NOMBRE_CATEGORIA VARCHAR2(100) NOT NULL,
    DESCRIPCION VARCHAR2(500),
    CONSTRAINT PK_CATEGORIA PRIMARY KEY (ID_CATEGORIA)
);

-- TABLA EVENTO
CREATE TABLE EVENTO (
    ID_EVENTO NUMBER(10) NOT NULL,
    NOMBRE VARCHAR2(100) NOT NULL,
    FECHA DATE NOT NULL,
    DESCRIPCION VARCHAR2(500),
    DURACION NUMBER(10),
    ID_UBICACION NUMBER(10) NOT NULL,
    ID_ORGANIZADOR NUMBER(10) NOT NULL,
    ID_CATEGORIA NUMBER(10) NOT NULL,
    CONSTRAINT PK_EVENTO PRIMARY KEY (ID_EVENTO),
    CONSTRAINT FK_EVENTO_UBICACION FOREIGN KEY (ID_UBICACION) REFERENCES UBICACION(ID_UBICACION),
    CONSTRAINT FK_EVENTO_ORGANIZADOR FOREIGN KEY (ID_ORGANIZADOR) REFERENCES ORGANIZADOR(ID_ORGANIZADOR),
    CONSTRAINT FK_EVENTO_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
);

-- TABLA INSCRIPCION
CREATE TABLE INSCRIPCION (
    ID_INSCRIPCION NUMBER(10) NOT NULL,
    FECHA_INSCRIPCION DATE NOT NULL,
    ID_USUARIO NUMBER(10) NOT NULL,
    ID_EVENTO NUMBER(10) NOT NULL,
    CONSTRAINT PK_INSCRIPCION PRIMARY KEY (ID_INSCRIPCION),
    CONSTRAINT FK_INSCRIPCION_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT FK_INSCRIPCION_EVENTO FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO(ID_EVENTO)
);